version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]

  db:
    ports:
      - "5433:5432"  # Different port to avoid conflicts with local postgres
